# Generated by Django 4.2.1 on 2023-06-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('comentarios', models.TextField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
    ]
